import Google from "@auth/core/providers/google";
import { convexAuth } from "@convex-dev/auth/server";

// Convex-native auth. The Google provider reads AUTH_GOOGLE_ID / AUTH_GOOGLE_SECRET
// from the Convex deployment env (set by the operator — see AUTH_SETUP.md). The JWT
// signing keys are generated by `npx @convex-dev/auth` during setup.
export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
  providers: [Google],
});
