// Single source of truth for the in-game "What's New" panel: parse the repo's
// CHANGELOG.md into src/generated/changelog.ts. Never hand-maintain that file — it is
// regenerated by the build (vite.config.ts plugin) and committed so tsc/tests resolve it.
//
// Grammar (the changelog is regular):
//   "## YYYY-MM-DD" (optionally "— suffix")  -> a dated section  (version = the date)
//   "## Unreleased (in progress)"            -> the in-progress section (version = "unreleased")
//   "- " lines                               -> entries under the current section
//   a leading "**Bold:**"                    -> the entry title; the rest is the body
//
// Run directly to regenerate: `node tools/genChangelog.mjs`

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { attachMedia } from "./changelogMedia.mjs";
import { writeChangelogSite } from "./genChangelogSite.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");

// Parse CHANGELOG markdown into the section/entry shape the panel renders.
export function parseChangelog(md) {
  const sections = [];
  let current = null;
  for (const rawLine of md.split("\n")) {
    const line = rawLine.trimEnd();
    const header = line.match(/^##\s+(.+)$/);
    if (header) {
      const label = header[1].trim();
      if (/unreleased/i.test(label)) {
        current = { version: "unreleased", date: "unreleased", entries: [] };
      } else {
        const date = label.match(/^(\d{4}-\d{2}-\d{2})/);
        const version = date ? date[1] : label;
        current = { version, date: version, entries: [] };
      }
      sections.push(current);
      continue;
    }
    if (!current) continue;
    const item = line.match(/^-\s+(.+)$/);
    if (!item) continue;
    const content = item[1].trim();
    const bold = content.match(/^\*\*(.+?)\*\*\s*(.*)$/);
    if (bold) {
      const title = bold[1].replace(/:\s*$/, "").trim();
      const body = bold[2].trim();
      current.entries.push(body ? { title, body } : { title, body: "" });
    } else {
      current.entries.push({ body: content });
    }
  }
  return sections;
}

function renderModule(sections) {
  const entryTs = (e) => {
    const parts = [];
    if (e.title !== undefined) parts.push(`title: ${JSON.stringify(e.title)}`);
    parts.push(`body: ${JSON.stringify(e.body)}`);
    if (e.media && e.media.length) parts.push(`media: ${JSON.stringify(e.media)}`);
    return `{ ${parts.join(", ")} }`;
  };
  const sectionTs = (s) => {
    const entries = s.entries.map((e) => `      ${entryTs(e)},`).join("\n");
    return `  {\n    version: ${JSON.stringify(s.version)},\n    date: ${JSON.stringify(s.date)},\n    entries: [\n${entries}\n    ],\n  },`;
  };
  return `// GENERATED FILE — do not edit by hand.
// Produced from CHANGELOG.md by tools/genChangelog.mjs (wired into the build via
// vite.config.ts). Edit the changelog, not this file.

export interface ChangelogEntry {
  title?: string;
  body: string;
  media?: string[]; // public URL paths of shipped sprite art, e.g. "/sprites/pets/wick.png"
}

export interface ChangelogSection {
  version: string;
  date: string;
  entries: ChangelogEntry[];
}

export const CHANGELOG: ChangelogSection[] = [
${sections.map(sectionTs).join("\n")}
];

// The newest section's version key (a date, or "unreleased"). The __BUILD_VERSION__
// define resolves to this at build time; this export is the runtime/test fallback.
export const LATEST_VERSION: string = CHANGELOG[0]?.version ?? "unreleased";
`;
}

// Regenerate src/generated/changelog.ts from CHANGELOG.md. Returns the latest version key.
export function writeChangelog(repoRoot = REPO_ROOT) {
  const md = readFileSync(join(repoRoot, "CHANGELOG.md"), "utf8");
  const sections = attachMedia(parseChangelog(md));
  const outDir = join(repoRoot, "src", "generated");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "changelog.ts"), renderModule(sections), "utf8");
  return sections[0]?.version ?? "unreleased";
}

// Compute the build version key without writing (used by the vite `define`).
export function latestVersion(repoRoot = REPO_ROOT) {
  const md = readFileSync(join(repoRoot, "CHANGELOG.md"), "utf8");
  return parseChangelog(md)[0]?.version ?? "unreleased";
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const version = writeChangelog();
  writeChangelogSite();
  process.stdout.write(`generated src/generated/changelog.ts + public/changelog/ (latest: ${version})\n`);
}
